server:
  port: 8090
spring:
  application:
    name: @artifactId@
  cloud:
    gateway:
      routes:
        # 系统服务
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
          # 路由过滤器
          filters:
            - RewritePath=/system/(?<segment>.*), /$\{segment}
        # 用户服务
        - id: user-portal
          uri: lb://user-portal
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: user-admin
          uri: lb://user-admin
          predicates:
            - Path=/admin/user/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /$\{segment}
        # 任务服务
        - id: task-portal
          uri: lb://task-portal
          predicates:
            - Path=/api/task/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: task-admin
          uri: lb://task-admin
          predicates:
            - Path=/admin/task/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /$\{segment}
app:
  # 参数签名验证
  decrypt:
    enabled: true
    privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALLqqKLygu/++O7WxEqIv+r6q3HBP/ya3AEgNW6W1TeXBfWMBnCiw1r3oqF58EOVzTVzkgMYHOj39XN2E6Lvhxw45beEx8RPAJ6rinBQrJAzFLYHc5I8xRjj1NXHs2IQMhT9tyT6xMHGRtOCJ2311SQiBypEyFg8nXcvq7G4QSoJAgMBAAECgYANPQ5B0lpsaiwetg77qd8zgp1Fc0RqC0Zcofa6Klh3/sl+1//Q/UYhuMGUm6pywcaXnifPaU0YUuKbSsEctQcE6KUFiWpwTqXqumM0Pt2kFnwm4iRtKwJYqsNIt7AWvujOUopjIaD8ExAcm67dgbHmZ8ZiFFrNxeHp5DDPhEbEoQJBANvUB0hs42XjkG5wMmxcTo61u+WLrvQ7imAeW0/CSCqmYxtoYLd2+2z8PA/8Mtmt7u9AHvn99I/OqYf0PLi521kCQQDQW0ib6MHxloJnZGgzYAEEt2I42pTFuARrPxdQZdp7E0qNa7oc5ElLx7LlMKvvj/RSRAXa8cPkJmjsUmqAT94xAkAIPBYVwXZ3P6IOcQeChaavs+EZBTWFkqFpXlm/UCDR8C+wPCW7Waqrd3tsgd8Jxnk33ygJ51h89pnlLOIFbXjpAkB5YSRch20ss3TGjMzTWRNezwJugo/22yvf2oJXeO6dknB1EJP8rtUwS2chc4hGaEN6BVyv3vYynFm1ipG2rFCRAkEAhiPPYJ7KZ1l3Omf7gst/P1PXsmoGTUUyh2VkRXKOdzN0b/ge6peBFKilqYkOZQDRW8qQCY8vuxgDCHIt5dywiA==
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCy6qii8oLv/vju1sRKiL/q+qtxwT/8mtwBIDVultU3lwX1jAZwosNa96KhefBDlc01c5IDGBzo9/VzdhOi74ccOOW3hMfETwCeq4pwUKyQMxS2B3OSPMUY49TVx7NiEDIU/bck+sTBxkbTgidt9dUkIgcqRMhYPJ13L6uxuEEqCQIDAQAB