spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.159.128:3306/admin?${mysql-param}
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: hikari-admin
      connection-test-query: SELECT 1
      idle-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
