server:
  port: 8081
spring:
  application:
    name: @artifactId@
  redis:
    # Redis数据库索引 默认为0
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码 默认为空
    password: 123456
    # 连接超时时间 毫秒
    timeout: 1000
    lettuce:
      pool:
        # 连接池最大连接数 使用负值表示没有限制
        max-active: 100
        # 控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
        max-total: 1000
        # 连接池最大阻塞等待时间 使用负值表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 配置多长时间(毫秒)进行检测需要关闭的空闲连接 默认-1不运行此功能
        time-between-eviction-runs: 60000