spring:
  data:
    mongodb:
      host: localhost
        # 验证数据库
        authentication-database: admin
        # 数据库
        database: test
        username: test
        # 需加引号
        password: '123456'
        port: 27017