spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?${mysql-param}
    username: root
    password: 123456
springfox:
  documentation:
    # 关闭ui
    swagger-ui:
      enabled: false
    # 关闭自动启动扫描注解
    auto-startup: false