spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?${mysql-param}
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl