spring:
  datasource:
    url: jdbc:mysql://192.168.164.128:3306/manager?${mysql-param}
    username: root
    password: 123456
  data:
    mongodb:
      host: 192.168.164.128
      # 验证数据库
      authentication-database: admin
      # 数据库
      database: test
      username: test
      # 需加引号
      password: '123456'
      port: 27017
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl